#!/bin/bash
### BEGIN INIT INFO
# Provides:          microondas
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Executa o programa microondas
# Description:       Este script inicia o programa executável microondas localizado em /usr/local/.
### END INIT INFO

PROG_PATH="/usr/local/microondas"
PROG_NAME="microondas"
PIDFILE="/var/run/$PROG_NAME.pid"
LOGFILE="/var/log/$PROG_NAME.log"

start() {
    echo "Iniciando $PROG_NAME..."
    if [ -f $PIDFILE ]; then
        echo "$PROG_NAME já está em execução."
        exit 1
    fi
    nohup $PROG_PATH >> $LOGFILE 2>&1 &
    echo $! > $PIDFILE
    echo "$PROG_NAME iniciado."
}

stop() {
    echo "Parando $PROG_NAME..."
    if [ ! -f $PIDFILE ]; then
        echo "$PROG_NAME não está em execução."
        exit 1
    fi
    kill $(cat $PIDFILE)
    rm -f $PIDFILE
    echo "$PROG_NAME parado."
}

restart() {
    stop
    start
}

status() {
    if [ -f $PIDFILE ]; then
        echo "$PROG_NAME está em execução."
    else
        echo "$PROG_NAME não está em execução."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Uso: $0 {start|stop|restart|status}"
        exit 1
esac
exit 0

